# In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow.

More specifically, we're going to cover:
* Introduction to tensores
* Getting information from tensors
* Manipulation tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPU with Tensorflow (or TPU)
* Exercises to try yourself!

In [2]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [4]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
# check dimensions of the vector
vector.ndim

1

In [8]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[9, 3],
                      [3,9]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 3],
       [3, 9]])>

In [9]:
# check the dimensions of the matrix
matrix.ndim

2

In [10]:
#create another matrix
another_matrix = tf.constant([[1., 2.],
                              [3., 4.],
                              [5., 6.]], dtype=tf.float16) #specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
#create a tensor
tensor = tf.constant([
                      [
                       [1, 2, 7],
                       [3, 4, 8],
                       [5, 6, 9]
                      ],
                      [
                       [1, 2, 7],
                       [3, 4, 8],
                       [5, 6, 9]
                      ]
                      ])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[1, 2, 7],
        [3, 4, 8],
        [5, 6, 9]],

       [[1, 2, 7],
        [3, 4, 8],
        [5, 6, 9]]])>

In [13]:
tensor.ndim

3

# what we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimesional array of number (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimesional tensor is a vector )

### Creating tensors with tf.Variable

In [14]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [15]:
 # let's try changing one of the elements in changable_tensor
 changeable_tensor[0].assign(7)
 changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [16]:
 # let's try changing one of the elements in unchangable_tensor
 unchangeable_tensor[0].assign(7)
 unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [17]:
random_1 = tf.random.Generator.from_seed(9)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(9)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967],
        [-0.29604465, -0.21134205]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967],
        [-0.29604465, -0.21134205]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [84]:
#shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([
    [1, 9],
    [2, 3],
    [3, 6],
])

# shuffle our not_shuffled tensor
tf.random.set_seed(42) # global level random seed
not_shuffled, tf.random.shuffle(not_shuffled, seed=42) # operation level random seed


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 9],
        [2, 3],
        [3, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 9],
        [2, 3],
        [3, 6]])>)

> If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

## Other way to make tensors

In [86]:
# create a tensor of ones
tf.ones([2,10])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [88]:
# create a tensor of zeros
tf.zeros([10, 2])

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>